Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"
  # config.vm.box = "generic/rocky8"
  # config.vm.box = "generic/ubuntu2004"
  config.vm.network "private_network", ip: "192.168.56.2"
  config.vm.network "forwarded_port", guest: 2112, host: 2112, host_ip: "127.0.0.1"
  config.vm.synced_folder ".", "/vagrant/cgroup-warden"
    
  config.vm.provision "initial", type: "shell", path: "initial.sh" do |s|
  end

  config.vm.provision "service", type: "shell", path: "service.sh" do |s|
  end

  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
    vb.memory = 4096 
    vb.cpus = 5
  end

end 

