{
 "title": "tests",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Unit Usage Aggregations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(systemd_unit_cpu_usage_ns[1m])",
     "legendFormat": "{{unit}}"
    },
    {
     "expr": "systemd_unit_cpu_limit_us_per_s*1000 >0",
     "legendFormat": "{{unit}} Limit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(systemd_unit_memory_current_bytes[5m])",
     "legendFormat": "{{unit}}"
    }
   ]
  },
  {
   "title": "CPU Usage Through Processes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum by(unit) (rate(procfs_pid_cpu_usage_ns[5m]))",
     "legendFormat": "{{unit}}"
    }
   ]
  },
  {
   "title": "Memory Usage Through Processes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(unit) (avg_over_time(procfs_pid_pss_bytes[10m]))",
     "legendFormat": "{{unit}}"
    }
   ]
  },
  {
   "title": "Policy queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true
  },
  {
   "title": "Violations for Policy with 1 Core, 1 GiB Thresholds",
   "type": "table",
   "gridPos": { "h": 20, "w": 7, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "(sum by (unit, instance) (rate(systemd_unit_cpu_usage_ns{instance=~\".*\"}[1m])) / 1000000000.0) > 1.0 or (sum by (unit, instance) (avg_over_time(systemd_unit_memory_current_bytes{instance=~\".*\"}[1m])) / 1073741824.0) > 1.0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Violations for Policy with 1 Core, 1 GiB Thresholds",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 17, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (unit, instance) (rate(systemd_unit_cpu_usage_ns{instance=~\".*\"}[15m])) / 1000000000.0) > 1.0 or (sum by (unit, instance) (avg_over_time(systemd_unit_memory_current_bytes{instance=~\".*\"}[15m])) / 1073741824.0) > 1.0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}