[django]
debug = false
allowed_hosts = ['your.site.edu', 'localhost']
time_zone = 'America/Denver'

[email]
host = 'mailhog'
port = '1025'
domain = 'test.site.edu'

[prometheus]
url = 'https://your.prometheus.host:9090'
verify_ssl = true

[warden]
bearer = 'super-secret-bearer-token'
verify_ssl = true
use_tls = true