# see provisioning.sh

TEST_ADDRESS = "192.168.56.2"
TEST_PORT = 2112
TEST_HOST = f"{TEST_ADDRESS}"
TEST_CONTROL_ENDPOINT = f"https://{TEST_HOST}:{TEST_PORT}/control"
TEST_METRICS_ENDPOINT = f"https://{TEST_HOST}:{TEST_PORT}/metrics"
TEST_CGROUP_AGENT_SECRET = "insecure-95axve4fn4j2u8ih0j1ltg272g1n297l8"
TEST_BEARER_TOKEN = f"Bearer {TEST_CGROUP_AGENT_SECRET}"

TEST_USER1 = "user-1001"
TEST_USER1_SLICE = f"{TEST_USER1}.slice"
TEST_USER2 = "user-1002"
TEST_USER2_SLICE = f"{TEST_USER2}.slice"
TEST_USER3 = "user-1003"
TEST_USER3_SLICE = f"{TEST_USER3}.slice"
TEST_USER4 = "user-1004"
TEST_USER4_SLICE = f"{TEST_USER4}.slice"
TEST_USER5 = "user-1005"
TEST_USER5_SLICE = f"{TEST_USER5}.slice"
TEST_USER_PASSWORD = "password"
