[django]
debug = true
allowed_hosts = ['host.docker.internal', 'localhost']
time_zone = 'America/Denver'

[email]
host = 'mailhog'
port = '1025'
domain = 'test.site.edu'

[prometheus]
url = 'http://prometheus:9090'
verify_ssl = false

[warden]
bearer = 'insecure-95axve4fn4j2u8ih0j1ltg272g1n297l8'
verify_ssl = false