version: '3.7'

volumes:
  prometheus_data: {}
  grafana-storage: {}

services:
  arbiter:
    image: mcr.microsoft.com/vscode/devcontainers/base:bookworm
    container_name: arbiter
    volumes:
      - ../..:/workspaces:cached
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: sleep infinity
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  keycloak:
    ports:
      - 8080:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    image: quay.io/keycloak/keycloak:26.2.5
    command: start-dev
