# Generated by Django 5.1.2 on 2024-10-18 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "dashboard",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Apply", "Limit Applied on a Target"),
                            ("Eval", "Policies Evaluated"),
                        ],
                        max_length=255,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_base_policy", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("domain", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True, max_length=1024)),
                ("penalty_constraints", models.JSONField()),
                ("penalty_duration", models.DurationField(null=True)),
                ("repeated_offense_scalar", models.FloatField(null=True)),
                ("repeated_offense_lookback", models.DurationField(null=True)),
                ("grace_period", models.DurationField(null=True)),
                ("query", models.TextField(max_length=1024)),
                ("query_parameters", models.JSONField(null=True)),
            ],
            options={
                "verbose_name_plural": "Policies",
            },
        ),
        migrations.CreateModel(
            name="BasePolicy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("arbiter.policy",),
        ),
        migrations.CreateModel(
            name="UsagePolicy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("arbiter.policy",),
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(max_length=255)),
                ("host", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("uid", models.IntegerField(null=True)),
                ("last_applied", models.JSONField()),
            ],
            options={
                "verbose_name_plural": "Targets",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("unit", "host", "username"), name="unique_target"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Violation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_base_status", models.BooleanField(default=False, editable=False)),
                ("expiration", models.DateTimeField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("offense_count", models.IntegerField(default=1, null=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="arbiter.policy"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="arbiter.target"
                    ),
                ),
            ],
        ),
    ]
