# Generated by Django 5.0.4 on 2024-05-14 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="timewindow",
            field=models.DurationField(
                default=datetime.timedelta(seconds=300),
                help_text="How far back Arbiter looks at usage (default 5m)",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="grace_period",
            field=models.DurationField(
                default=datetime.timedelta(seconds=180),
                help_text="How long after a violation/penalty expires until the unit/host can violate this policy again",
            ),
        ),
    ]
