# Generated by Django 5.1.3 on 2024-11-07 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="target",
            old_name="last_applied",
            new_name="limits",
        ),
    ]
