# Generated by Django 5.1.2 on 2024-10-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="query_parameters",
        ),
        migrations.AlterField(
            model_name="policy",
            name="query",
            field=models.JSONField(null=True),
        ),
    ]
