# Generated by Django 5.1.1 on 2024-10-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0002_policy_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="is_active",
        ),
        migrations.AddField(
            model_name="policy",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Whether or not this policy gets evaluated"
            ),
        ),
    ]
