# Generated by Django 5.0.6 on 2024-06-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0002_policy_timewindow_alter_policy_grace_period"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="target",
            name="unique_target",
        ),
        migrations.AddField(
            model_name="target",
            name="username",
            field=models.CharField(default="unknown username", max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                fields=("unit", "username", "host"), name="unique_target"
            ),
        ),
    ]
