# Generated by Django 5.1.2 on 2024-10-21 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0003_alter_policy_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="lookback",
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
        migrations.AlterField(
            model_name="policy",
            name="grace_period",
            field=models.DurationField(
                default=datetime.timedelta(seconds=300), null=True
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="penalty_duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=900), null=True
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="repeated_offense_lookback",
            field=models.DurationField(
                default=datetime.timedelta(seconds=10800), null=True
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="repeated_offense_scalar",
            field=models.FloatField(default=1.0, null=True),
        ),
    ]
