# Generated by Django 5.1.3 on 2024-11-14 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0002_rename_last_applied_target_limits"),
        ("arbiter", "0003_remove_policy_is_active_policy_active"),
    ]

    operations = []
