# Generated by Django 5.1 on 2024-09-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0003_remove_target_unique_target_target_username_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="target",
            name="unique_target",
        ),
        migrations.RemoveField(
            model_name="target",
            name="username",
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                fields=("unit", "host"), name="unique_target"
            ),
        ),
    ]
