# Generated by Django 5.1 on 2024-09-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "arbiter",
            "0004_remove_target_unique_target_remove_target_username_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="operation",
            field=models.CharField(
                choices=[
                    (">", "Greater Than"),
                    ("<", "Less Than"),
                    ("==", "Enabled"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="type",
            field=models.CharField(
                choices=[
                    ("int", "Integer"),
                    ("float", "Floating Point"),
                    ("bool", "Boolean"),
                ],
                max_length=255,
            ),
        ),
    ]
