# Generated by Django 5.1.2 on 2024-10-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0004_policy_lookback_alter_policy_grace_period_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dashboard",
        ),
        migrations.AlterField(
            model_name="target",
            name="last_applied",
            field=models.JSONField(blank=True),
        ),
    ]
