# Generated by Django 5.1.1 on 2024-10-23 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0004_policy_lookback_alter_policy_grace_period_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="policy",
            old_name="query",
            new_name="query_data",
        ),
    ]
