# Generated by Django 5.1.2 on 2024-10-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0005_alter_property_operation_alter_property_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="target",
            name="unique_target",
        ),
        migrations.AddField(
            model_name="target",
            name="username",
            field=models.CharField(default="unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="violation",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                fields=("unit", "host", "username"), name="unique_target"
            ),
        ),
    ]
