# Generated by Django 5.1.2 on 2024-10-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0005_delete_dashboard_alter_target_last_applied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="last_applied",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
