# Generated by Django 5.1.1 on 2024-10-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0005_rename_query_policy_query_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="target",
            name="last_applied",
            field=models.JSONField(default=dict),
        ),
    ]
