# Generated by Django 5.1.2 on 2024-10-21 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0006_alter_target_last_applied"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="target",
            name="uid",
        ),
    ]
