# Generated by Django 5.1.2 on 2024-10-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0006_remove_target_unique_target_target_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="penalty",
            name="is_default_status",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="policy",
            name="is_base_policy",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
