# Generated by Django 5.1.2 on 2024-10-22 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0007_remove_target_uid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="target",
            old_name="last_applied",
            new_name="limits",
        ),
    ]
