# Generated by Django 5.1.2 on 2024-10-16 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0007_penalty_is_default_status_policy_is_base_policy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="penalty",
            old_name="is_default_status",
            new_name="is_base_constraint",
        ),
        migrations.AddField(
            model_name="violation",
            name="is_base_status",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=300), null=True
            ),
        ),
        migrations.AlterField(
            model_name="violation",
            name="expiration",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="violation",
            name="offense_count",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
