# Generated by Django 5.1.2 on 2024-10-18 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "arbiter",
            "0008_rename_is_default_status_penalty_is_base_constraint_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Violation",
            new_name="Status",
        ),
        migrations.RemoveField(
            model_name="limit",
            name="property",
        ),
        migrations.RemoveField(
            model_name="penalty",
            name="limits",
        ),
        migrations.RemoveField(
            model_name="target",
            name="last_applied",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="penalty",
        ),
        migrations.CreateModel(
            name="BasePolicy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("arbiter.policy",),
        ),
        migrations.CreateModel(
            name="UsagePolicy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("arbiter.policy",),
        ),
        migrations.RemoveField(
            model_name="policy",
            name="grace_period",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="lookback_window",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="query_params",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="timewindow",
        ),
        migrations.AddField(
            model_name="policy",
            name="constraints",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policy",
            name="duration",
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="grace",
            field=models.DurationField(
                default=datetime.timedelta(seconds=900), null=True
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="scale",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="target",
            name="uid",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="policy",
            name="query",
            field=models.TextField(max_length=1024),
        ),
        migrations.DeleteModel(
            name="Property",
        ),
        migrations.DeleteModel(
            name="Limit",
        ),
        migrations.AddField(
            model_name="target",
            name="last_applied",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Penalty",
        ),
    ]
