# Generated by Django 5.1.2 on 2024-10-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "arbiter",
            "0008_rename_is_default_status_penalty_is_base_constraint_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="limit",
            name="property",
        ),
        migrations.CreateModel(
            name="BasePolicy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("arbiter.policy",),
        ),
        migrations.CreateModel(
            name="UsagePolicy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("arbiter.policy",),
        ),
        migrations.AddField(
            model_name="limit",
            name="prop",
            field=models.CharField(
                choices=[
                    ("CPUQuotaPerSecUSec", "CPU Quota"),
                    ("MemoryMax", "Memory Maximum"),
                    ("MemoryHigh", "Memory Maximum"),
                ],
                default="MemoryMax",
                max_length=225,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="limit",
            name="value",
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name="Property",
        ),
    ]
