# Generated by Django 5.1.2 on 2024-10-17 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0009_remove_limit_property_basepolicy_usagepolicy_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Violation",
            new_name="Status",
        ),
        migrations.RemoveField(
            model_name="penalty",
            name="limits",
        ),
        migrations.RemoveField(
            model_name="target",
            name="last_applied",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="penalty",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="grace_period",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="lookback_window",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="query_params",
        ),
        migrations.RemoveField(
            model_name="policy",
            name="timewindow",
        ),
        migrations.AddField(
            model_name="policy",
            name="constraints",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policy",
            name="duration",
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name="policy",
            name="grace",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policy",
            name="lookback",
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policy",
            name="scale",
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="target",
            name="uid",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="policy",
            name="query",
            field=models.TextField(max_length=1024),
        ),
        migrations.DeleteModel(
            name="Limit",
        ),
        migrations.AddField(
            model_name="target",
            name="last_applied",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Penalty",
        ),
    ]
