# Generated by Django 5.1.2 on 2024-10-17 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0010_rename_violation_status_remove_penalty_limits_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="lookback",
        ),
        migrations.AlterField(
            model_name="policy",
            name="grace",
            field=models.DurationField(
                default=datetime.timedelta(seconds=900), null=True
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="scale",
            field=models.FloatField(null=True),
        ),
    ]
