# Generated by Django 5.1.1 on 2024-10-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
