# Generated by Django 5.1.6 on 2025-02-10 19:56

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0004_merge_20241114_1237"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="target",
            name="unique_target",
        ),
        migrations.AddField(
            model_name="target",
            name="port",
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="target",
            constraint=models.UniqueConstraint(
                fields=("host", "username"), name="unique_target"
            ),
        ),
    ]
