# Generated by Django 5.1.6 on 2025-06-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0006_arbuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="watcher_mode",
            field=models.BooleanField(
                default=False,
                help_text="If set, the policy will only report/email violations and not enforce limits",
            ),
        ),
    ]
