# Generated by Django 5.1.6 on 2025-06-24 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0008_refresh_queries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={
                "permissions": [
                    (
                        "arbiter_view",
                        "can see user status/usage/violations, as well as everything else",
                    ),
                    (
                        "arbiter_administrator",
                        "can set limits and evaluate on dashboard and change/create policies",
                    ),
                ],
                "verbose_name_plural": "Policies",
            },
        ),
        migrations.AlterField(
            model_name="policy",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="optional description for the purpose/overview of this policy",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="domain",
            field=models.CharField(
                help_text="regex for the hostname/instance where this policy is in affect",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="grace_period",
            field=models.DurationField(
                default=datetime.timedelta(seconds=300),
                help_text="for how long after leaving penalty status the user is unable to violate this policy for",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="lookback",
            field=models.DurationField(
                default=datetime.timedelta(seconds=900),
                help_text="How far back arbiter evaluates user's usage (e.g. if a user's average usage is above the threshold(s) for this amount of time, they will be in violation)",
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="name",
            field=models.CharField(
                help_text="Name of the policy", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="penalty_constraints",
            field=models.JSONField(
                help_text="The limits that will be applied at each tier of penalty . Repeated violation ups the penalty tier."
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="penalty_duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=900),
                help_text="how long a user will be in penalty status upon violation (can scale depending on other settings)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="repeated_offense_lookback",
            field=models.DurationField(
                default=datetime.timedelta(seconds=10800),
                help_text="How far back arbiter looks at violation history (e.g. if set to 3 hours and the current violator has 2 violations in the past 3 hours, the user will be in tier 2 penalty status and with a proportionally scaled duration )",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="repeated_offense_scalar",
            field=models.FloatField(
                default=1.0,
                help_text="How much a penalty's duration scales each repeated violation (e.g. if set to 1.0 the duration will double the second repeat violation and triple for the third repeat violation)",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="ArbUser",
        ),
    ]
