# Generated by Django 5.1.6 on 2025-06-24 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0008_refresh_queries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={
                "permissions": [
                    (
                        "staff",
                        "can see user status/usage/violations, as well as everything else",
                    ),
                    (
                        "administrator",
                        "can set limits and evaluate on dashboard and change/create policies",
                    ),
                ],
                "verbose_name_plural": "Policies",
            },
        ),
        migrations.DeleteModel(
            name="ArbUser",
        ),
    ]
