# Generated by Django 5.1.6 on 2025-07-02 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arbiter", "0009_alter_policy_options_alter_policy_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={
                "permissions": [
                    ("arbiter_view", "Arbiter Viewer"),
                    ("arbiter_administrator", "Arbiter Administrator"),
                ],
                "verbose_name_plural": "Policies",
            },
        ),
    ]
